services:
  api:
    image: mcr.microsoft.com/dotnet/sdk:10.0
    restart: unless-stopped
    working_dir: /src
    ports:
      - "5000:8080"
    dns:
      - 8.8.8.8
      - 1.1.1.1
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_USE_POLLING_FILE_WATCHER=true
      - ASPNETCORE_URLS=http://0.0.0.0:8080
    volumes:
      - ./backend/srv:/src
      - ./Application-web:/app/webApp
      - uploads_data:/src/wwwroot/uploads
    command: dotnet watch run --no-launch-profile
    env_file:
      - .env

  web-prod:
    build:
      context: ./Application-web
      dockerfile: Dockerfile
    ports:
      - "420:80"
    depends_on:
      - api

  web-dev:
    build:
      context: ./Application-web
      dockerfile: Dockerfile.dev
    ports:
      - "421:5173"
    volumes:
      - ./Application-web:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - VITE_HMR_CLIENT_PORT=421
    stdin_open: true
    tty: true
    depends_on:
      - api

volumes:
  uploads_data: